### ISSUE TITLE
Broken backend website link

### ISSUE THREAD

**Issue by salikadave** [shahpreetk/beproject-backend#1]
Hey @shahpreetk , nice project 😁

I tried opening https://onlinebooking-backend.herokuapp.com/ it returns this:

![image](https://user-images.githubusercontent.com/35625827/117298102-9863c400-ae94-11eb-8679-ee04759d4f5a.png)

Postman says its a `404` , you might want to consider sorting this issue.

**Comment by shahpreetk** [comment]
Hey @salikadave,
Thank you for the feedback.

Also, with regards to the issue, a signup/login would be required in order to get any data and so Postman is returning a status of ```404```.   
If you'd like to signup you can do so by posting a request to https://onlinebooking-backend.herokuapp.com/users

So since this is as per design, I'll be closing this issue

Thanks again!😁
